"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <Daniel Pang> and <FULL NAME>, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: Dmp3577
UT EID 2:
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    biggest = 0
    for i in range(n):
        for j in range(i+1, n+1):
            substring = s[i:j]
            freq = {}
            for char in substring:
                if char in freq:
                    break
                freq[char] = 1
            else:
                if len(substring) > biggest:
                    biggest = max(len(substring), biggest)
    return biggest

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    biggest = 0
    for i in range(n):
        freq = [0]*256 #256 ASCII characters
        is_substring = True
        for j in range(i, n):
            asci = ord(s[j])
            freq[asci] += 1
            if freq[asci] > 1:
                is_substring = False
            if is_substring:
                biggest = max(biggest, j-i+1)
    return biggest

def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    biggest = 0
    left = 0
    freq = [0]*256 #256 ASCII characters
    for right in range(n):
        asci = ord(s[right])
        freq[asci] += 1
        while freq[asci] > 1:
            freq[ord(s[left])] -= 1
            left += 1
        if (right-left+1) > biggest:
            biggest = max(biggest, right-left+1)
    return biggest
